# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eCommerceDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from UserInformation import *
from API_Service import *


class Ui_MainWindow(object):
	def __init__(self):
		self.apiService: APIService = APIService()
		self.currentWatchList = self.__getCurrentWatchList()
		self.userInfo = self.__getCurrentUserInfo()
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(1070, 723)
		MainWindow.setWindowTitle("Product Monitoring")
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
		self.verticalLayoutWidget.setGeometry(QtCore.QRect(-20, 40, 1081, 571))
		self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
		self.mainVertical = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
		self.mainVertical.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
		self.mainVertical.setContentsMargins(0, 0, 0, 0)
		self.mainVertical.setObjectName("mainVertical")
		# product line start here ----------------------------------
		self.showWatchList()
		# product line ends here -----------------------------------
		self.hr = QtWidgets.QFrame(self.verticalLayoutWidget)
		self.hr.setFrameShape(QtWidgets.QFrame.HLine)
		self.hr.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.hr.setObjectName("hr")
		self.mainVertical.addWidget(self.hr)
		self.newItemHorizontal = QtWidgets.QHBoxLayout()
		self.newItemHorizontal.setSpacing(9)
		self.newItemHorizontal.setObjectName("newItemHorizontal")
		spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.newItemHorizontal.addItem(spacerItem1)
		self.addProductButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.addProductButton.sizePolicy().hasHeightForWidth())
		self.addProductButton.setSizePolicy(sizePolicy)
		self.addProductButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.addProductButton.setStyleSheet("background: blue;\n"
	"color: whitesmoke;\n"
	"border-radius: 10px;\n"
	"height: 50%;\n"
	"padding: 0px 5px;")
		self.addProductButton.setText("Add Item to WatchList")
		self.addProductButton.setObjectName("addProductButton")
		self.newItemHorizontal.addWidget(self.addProductButton)
		spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.newItemHorizontal.addItem(spacerItem2)
		self.mainVertical.addLayout(self.newItemHorizontal)
		self.emailLabel = QtWidgets.QLabel(self.centralwidget)
		self.emailLabel.setGeometry(QtCore.QRect(820, 0, 131, 31))
		self.emailLabel.setText("TextLabel")
		self.emailLabel.setObjectName("emailLabel")
		self.emailChangeButton = QtWidgets.QPushButton(self.centralwidget)
		self.emailChangeButton.setGeometry(QtCore.QRect(950, 0, 112, 34))
		self.emailChangeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.emailChangeButton.setText("Change Email")
		self.emailChangeButton.setObjectName("emailChangeButton")
		self.line = QtWidgets.QFrame(self.centralwidget)
		self.line.setGeometry(QtCore.QRect(0, 30, 1051, 20))
		self.line.setFrameShape(QtWidgets.QFrame.HLine)
		self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line.setObjectName("line")
		MainWindow.setCentralWidget(self.centralwidget)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		pass

	def showWatchList(self):
		i = 0
		# for product in self.currentWatchList:
		self.productHorizontal = QtWidgets.QHBoxLayout()
		self.productHorizontal.setObjectName("productHorizontal_{0}".format(i))
		spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
		self.productHorizontal.addItem(spacerItem)
		self.productNameLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
		self.productNameLabel.setEnabled(True)
		self.productNameLabel.setText("productName")
		self.productNameLabel.setObjectName("productNameLabel")
		self.productHorizontal.addWidget(self.productNameLabel)
		self.currentPriceLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
		self.currentPriceLabel.setText("productPrice")
		self.currentPriceLabel.setObjectName("currentPriceLabel")
		self.productHorizontal.addWidget(self.currentPriceLabel)
		self.desiredPriceLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
		self.desiredPriceLabel.setText("desiredPrice")
		self.desiredPriceLabel.setObjectName("desiredPriceLabel")
		self.productHorizontal.addWidget(self.desiredPriceLabel)
		self.verticalLayout = QtWidgets.QVBoxLayout()
		self.verticalLayout.setObjectName("verticalLayout")
		self.editProductButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
		self.editProductButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.editProductButton.setStyleSheet("background: rgb(85, 170, 255);\n"
	"border-radius: 10px;\n"
	"height: 50%;")
		self.editProductButton.setText("Edit Item Info")
		self.editProductButton.setObjectName("editProductButton")
		self.verticalLayout.addWidget(self.editProductButton)
		self.deleteProductButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
		self.deleteProductButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.deleteProductButton.setStyleSheet("background: rgb(255, 74, 74);\n"
	"border-radius: 10px;\n"
	"height: 50%;")
		self.deleteProductButton.setText("Delete Item")
		self.deleteProductButton.setObjectName("deleteProductButton")
		self.verticalLayout.addWidget(self.deleteProductButton)
		self.productHorizontal.addLayout(self.verticalLayout)
		self.productDropdownButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.productDropdownButton.sizePolicy().hasHeightForWidth())
		self.productDropdownButton.setSizePolicy(sizePolicy)
		self.productDropdownButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
		self.productDropdownButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.productDropdownButton.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.productDropdownButton.setAutoFillBackground(False)
		self.productDropdownButton.setStyleSheet("")
		self.productDropdownButton.setText("URL Dropdown")
		self.productDropdownButton.setObjectName("productDropdownButton")
		self.productHorizontal.addWidget(self.productDropdownButton)
		self.mainVertical.addLayout(self.productHorizontal)
		i += 1

	def __getCurrentWatchList(self):
		self.currentWatchList = self.apiService.getWatchList()
		print(json.dumps([item.__dict__ for item in self.currentWatchList]))
		
	def __getCurrentUserInfo(self):
		self.currentUserInfo = self.apiService.getUserInfo()
		print(self.currentUserInfo)
